services:
  # Backend FastAPI application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://dev-user:password@postgres:5432/dev_db
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      ENVIRONMENT: local
    profiles:
      - local
      # - test
    networks:
      - ollama-docker

  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    profiles:
      - local

  # Postgres database for development
  postgres:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    profiles:
      - local

  # Ollama service
  # ollama:
  #   image: docker.io/ollama/ollama:latest
  #   ports:
  #     - 7869:11434
  #   volumes:
  #     - .:/code
  #     - ./ollama/ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #     - OLLAMA_HOST=0.0.0.0
  #   networks:
  #     - ollama-docker

volumes:
  db-data:
  # langfuse_postgres_data:
  #   driver: local
  # langfuse_clickhouse_data:
  #   driver: local
  # langfuse_clickhouse_logs:
  #   driver: local
  # langfuse_minio_data:
  #   driver: local

networks:
  ollama-docker:
    external: false