"""Create users table

Revision ID: ac192ead293f
Revises: 
Create Date: 2025-04-30 20:06:34.748809

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac192ead293f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Password context for hashing

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'guest', name='userrolesenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
    
    # Insert admin user with password "12345@"
    op.bulk_insert(
        sa.table(
            'users',
            sa.column('email', sa.String),
            sa.column('first_name', sa.String),
            sa.column('last_name', sa.String),
            sa.column('hashed_password', sa.String),
            sa.column('active', sa.Boolean),
            sa.column('role', sa.Enum('admin', 'user', 'guest', name='userrolesenum')),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True)),
        ),
        [
            {
                'email': 'admin@example.com',
                'first_name': 'Admin',
                'last_name': 'User',
                'hashed_password': "$2b$12$iJfvuRj6Ml2Ilafb3Q8jGe/ihaxOK/vQ1ov6G1qPBolh5Usn9cNxO",
                'active': True,
                'role': 'admin',
                'created_at': datetime.now(),
                'updated_at': datetime.now(),
            }
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
